//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace ConnectIn
{
    using System;
    using System.Collections.Generic;
using System.Web;
    
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public string PhotoPath { get; set; }
        public string UserId { get; set; }
        public bool IsProfilePicture { get; set; }
        [Required(ErrorMessage = "Please select an image file")]
        public HttpPostedFileBase File { get; set; }
    }
}
